io.doe.service.failure.message=Something wrong !!
io.doe.service.duplicated.message=Duplicated resource '{0}'

io.doe.validation.constraints.FromTo.message=End date ({1}) should be after start date ({0})
io.doe.validation.constraints.FromToInterval.message=End date ({2}) should be after start date ({1}) at least more than '{0}' minutes
io.doe.validation.constraints.FutureMoreThan.message={name} ({validatedValue}) should be a future date more than '{minutes}' minutes from now

io.doe.validation.exceptions.TypeMismatch.message=Input value '{0}' does not match with type '{1}'
io.doe.validation.exceptions.TypeMismatchException.message=Failed to convert '{0}' type '{1}' field with value '{2}'
io.doe.validation.exceptions.MissingServletRequestParameterException.message='{0}' type parameter '{1}' is not present
io.doe.validation.exceptions.MissingServletRequestPartException.message=Part '{0}' is not present
